language: go

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get github.com/tsenart/deadcode
  - go get github.com/kisielk/errcheck

script:
  - go vet
  - golint
  - deadcode
  - $HOME/gopath/bin/goveralls -v -service=travis-ci -flags -test.timeout -flags 15s

go:
  - 1.8
  - 1.9
